# Generated by Django 2.2.4 on 2019-08-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_auto_20190807_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
