# Generated by Django 2.2.4 on 2019-08-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
